export const CREATE_FIELD_REQUEST = 'CREATE_FIELD_REQUEST';
export const CREATE_FIELD_FAILURE = 'CREATE_FIELD_FAILURE';
export const CREATE_FIELD_SUCCESS = 'CREATE_FIELD_SUCCESS';

export const UPDATE_FIELD_REQUEST = 'UPDATE_FIELD_REQUEST';
export const UPDATE_FIELD_FAILURE = 'UPDATE_FIELD_FAILURE';
export const UPDATE_FIELD_SUCCESS = 'UPDATE_FIELD_SUCCESS';

export const DELETE_FIELD_REQUEST = 'DELETE_FIELD_REQUEST';
export const DELETE_FIELD_FAILURE = 'DELETE_FIELD_FAILURE';
export const DELETE_FIELD_SUCCESS = 'DELETE_FIELD_SUCCESS';
