export const FETCH_FIELDS_REQUEST = 'FETCH_FIELDS_REQUEST';
export const FETCH_FIELDS_FAILURE = 'FETCH_FIELDS_FAILURE';
export const FETCH_FIELDS_SUCCESS = 'FETCH_FIELDS_SUCCESS';

export const CREATE_FIELD_REQUEST = 'CREATE_FIELD_REQUEST';
export const CREATE_FIELD_FAILURE = 'CREATE_FIELD_FAILURE';
export const CREATE_FIELD_SUCCESS = 'CREATE_FIELD_SUCCESS';

export const UPDATE_FIELD_REQUEST = 'UPDATE_FIELD_REQUEST';
export const UPDATE_FIELD_FAILURE = 'UPDATE_FIELD_FAILURE';
export const UPDATE_FIELD_SUCCESS = 'UPDATE_FIELD_SUCCESS';

export const DELETE_FIELD_REQUEST = 'DELETE_FIELD_REQUEST';
export const DELETE_FIELD_FAILURE = 'DELETE_FIELD_FAILURE';
export const DELETE_FIELD_SUCCESS = 'DELETE_FIELD_SUCCESS';

export const FETCH_MAPPINGS_REQUEST = 'FETCH_MAPPINGS_REQUEST';
export const FETCH_MAPPINGS_FAILURE = 'FETCH_MAPPINGS_FAILURE';
export const FETCH_MAPPINGS_SUCCESS = 'FETCH_MAPPINGS_SUCCESS';

export const FETCH_UNMAPPED_ENDPOINTS_REQUEST = 'FETCH_UNMAPPED_ENDPOINTS_REQUEST';
export const FETCH_UNMAPPED_ENDPOINTS_FAILURE = 'FETCH_UNMAPPED_ENDPOINTS_FAILURE';
export const FETCH_UNMAPPED_ENDPOINTS_SUCCESS = 'FETCH_UNMAPPED_ENDPOINTS_SUCCESS';

export const FETCH_MAPPING_FIELD_SUGGESTIONS_REQUEST = 'FETCH_MAPPING_FIELD_SUGGESTIONS_REQUEST';
export const FETCH_MAPPING_FIELD_SUGGESTIONS_FAILURE = 'FETCH_MAPPING_FIELD_SUGGESTIONS_FAILURE';
export const FETCH_MAPPING_FIELD_SUGGESTIONS_SUCCESS = 'FETCH_MAPPING_FIELD_SUGGESTIONS_SUCCESS';

export const CREATE_MAPPING_REQUEST = 'CREATE_MAPPING_REQUEST';
export const CREATE_MAPPING_FAILURE = 'CREATE_MAPPING_FAILURE';
export const CREATE_MAPPING_SUCCESS = 'CREATE_MAPPING_SUCCESS';

export const UPDATE_MAPPING_REQUEST = 'UPDATE_MAPPING_REQUEST';
export const UPDATE_MAPPING_FAILURE = 'UPDATE_MAPPING_FAILURE';
export const UPDATE_MAPPING_SUCCESS = 'UPDATE_MAPPING_SUCCESS';

export const DELETE_MAPPING_REQUEST = 'DELETE_MAPPING_REQUEST';
export const DELETE_MAPPING_FAILURE = 'DELETE_MAPPING_FAILURE';
export const DELETE_MAPPING_SUCCESS = 'DELETE_MAPPING_SUCCESS';
